![](exercise_5_8_1.png)
![](exercise_5_8_2.png)
![](off_policy_mc_control.png)

In [3]:
def off_policy_mc_control():
    
    action_value = {}
    normalizing_constant = {}
    target_policy = {}  # The target policy is the greedy policy.
    
    count = 1

    while True:
        
        behaviour_policy = epsilon_greedy_policy(target_policy, EPSILON)
        
        if DEBUG:
            ipdb.set_trace()
        
        start_state = random.choice(START_STATES)
        episode = run_episode(behaviour_policy, start_state)
        episode = list(reversed(x))
        
        G = 0
        W = 1
        
        # Iterate in tuples (t + 1, t)
        for new_state, new_action, new_reward, state, action, reward in zip(episode, episode[1:]):
            
            G = GAMMA * G + new_reward
            
            normalizing_constant[(state, action)] = normalizing_constant.get((state, action), 0) + W
            
            action_value[(state, action)] = (
                action_value.get((state, action), 0) +
                W / normalizing_constant.get((state, action), 0) * (G - action_value.get((state, action), 0))
            )
            
            target_policy[state] = best_action(state, action_value)
            
            if action != target_policy[state]:
                break
                
            W = W / behaviour_policy(state, action)


def run_episode(behaviour_policy, start_state):
    """Used to generate an episode.
    """
    ipdb.set_trace()
    
    # Initialize episode at start state, the 0 action, and 0 reward.
    state = start_state
    episode = [(start_state, 0, 0)]
    
    while cell_type(state) != 'GOAL':
        
        action = behaviour_policy(state)
        
        state = move_car(state, action)
        
        episode.append(
            (state, action, -1)
        )
        
        print_trace(episode)
    
    return episode


def print_trace(episode):
    map_ =  MAP.copy()
    for state, action, reward in episode:
        x, y, dx, dy = state
        map_[x, y] = reward
    print(map_)


def epsilon_greedy_policy(target_policy, epsilon = 0.1):
    def policy(state):
        if random.random() <= epsilon:
            return random.choice(list(actions(state)))
        return target_policy.get(state, (0, 0))
    return policy


def best_action(state, action_value):
    """Returns the best action in a state using the action values.
    """
    state_action_value = [(action_value.get((state, action), 0), action) for action in actions(state)]
    return max(zip(state_action_value, range(len(state_action_value))))[1]

#off_policy_mc_control()

In [ ]:
start_state = random.choice(START_STATES)
def exploring_policy(state):
    return random.choice(list(actions(state)))
episode = run_episode(exploring_policy, start_state)
print_trace(episode)

> <ipython-input-3-a68bb5cf343d>(49)run_episode()
     48     # Initialize episode at start state, the 0 action, and 0 reward.
---> 49     state = start_state
     50     episode = [(start_state, 0, 0)]

ipdb> n
> <ipython-input-3-a68bb5cf343d>(50)run_episode()
     49     state = start_state
---> 50     episode = [(start_state, 0, 0)]
     51 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(52)run_episode()
     51 
---> 52     while cell_type(state) != 'GOAL':
     53 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(54)run_episode()
     53 
---> 54         action = behaviour_policy(state)
     55 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(56)run_episode()
     55 
---> 56         state = move_car(state, action)
     57 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(58)run_episode()
     57 
---> 58         episode.append(
     59             (state, action, -1)

ipdb> n
> <ipython-input-3-a68bb5cf343d>(59)run_episode()
     58         episode.append(
---> 59             (state, action, -1)
     60 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(54)run_episode()
     53 
---> 54         action = behaviour_policy(state)
     55 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(56)run_episode()
     55 
---> 56         state = move_car(state, action)
     57 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(58)run_episode()
     57 
---> 58         episode.append(
     59             (state, action, -1)

ipdb> n
> <ipython-input-3-a68bb5cf343d>(59)run_episode()
     58         episode.append(
---> 59             (state, action, -1)
     60         )

ipdb> n
> <ipython-input-3-a68bb5cf343d>(62)run_episode()
     61 
---> 62         print_trace(episode)
     63 

ipdb> n
[[ 0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(62)run_episode()
     61 
---> 62         print_trace(episode)
     63 

ipdb> n
[[ 0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(54)run_episode()
     53 
---> 54         action = behaviour_policy(state)
     55 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(56)run_episode()
     55 
---> 56         state = move_car(state, action)
     57 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(58)run_episode()
     57 
---> 58         episode.append(
     59             (state, action, -1)

ipdb> n
> <ipython-input-3-a68bb5cf343d>(59)run_episode()
     58         episode.append(
---> 59             (state, action, -1)
     60         )

ipdb> n
> <ipython-input-3-a68bb5cf343d>(62)run_episode()
     61 
---> 62         print_trace(episode)
     63 

ipdb> n
[[ 0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1 

ipdb> n
> <ipython-input-3-a68bb5cf343d>(62)run_episode()
     61 
---> 62         print_trace(episode)
     63 

ipdb> n
[[ 0  0  0  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  0  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  2]
 [ 1  1  1  1  1  1  1  1  1  1  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1  1  1  1  1  1  1  0  0  0  0  0  0  0]
 [ 0  1  1 

In [30]:
%debug

> <ipython-input-20-f80a67a09e5e>(28)cell_type()
     26 def cell_type(state):
     27     x, y, dx, dy = state
---> 28     return CELL_TYPE_MAP[MAP[x, y]]
     29 
     30 

ipdb> state
(32, 3, 1, 0)
--KeyboardInterrupt--
ipdb> c


# Implementation

In [1]:
import pandas as pd
import numpy as np
from itertools import product
import random
import ipdb

DEBUG = False


MAP = pd.read_csv('maps/map1.csv', header=None).values
CELL_TYPE_MAP = {
    0: 'WALL',
    1: 'TRACK',
    2: 'GOAL',
    3: 'START',
}

EPSILON = 0.1

def states():
    """Generates all possible states.
    """
    for x, y in product(range(MAP.shape[0]), range(MAP.shape[1])):
        yield (x, y)
        
def cell_type(state):
    x, y, dx, dy = state
    try:
        return CELL_TYPE_MAP[MAP[x, y]]
    except IndexError:
        return 'WALL'


START_STATES = list(filter(
    lambda state: cell_type(state) == 'START',
    [(x, y, 0, 0) for x, y in product(range(MAP.shape[0]), range(MAP.shape[1]))]
))

In [2]:
def actions(state):
    """Generate all velocity vectors at a given state.
    """
    _, _, dx, dy = state
    
    for ddx in [-1, 0, 1]:
        for ddy in [-1, 0, 1]:
            
            new_dx = dx + ddx
            new_dy = dy + ddy
            
            
            # Both velocity components are restricted to be positive and less than 5.
            if not (0 <= new_dx <= 5 and 0 <= new_dy <= 5):
                continue
            
            yield (new_dx, new_dy)
            

def move_car(state, action):
    """Move a car using the new velocity vector.
    """
    x, y, dx, dy = state
    ddx, ddy = action
    
    new_dx = dx + ddx
    new_dy = dy + ddy
    
    new_x = x + new_dx
    new_y = y + new_dy
    
    new_state = (new_x, new_y, new_dx, new_dy)

    if cell_type(new_state) == 'WALL':
        return random.choice(START_STATES)
    return new_state
            
assert len(list(actions((0, 0, 1, 1)))) == 9, 'total of 9 actions.'
assert move_car((1, 1, 1, 1), (1, 1)) == (3, 3, 2, 2)

(3, 3, 2, 2)

[[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
 [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
 [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 1, 0,